# ==============================
# BASE DE DATOS MYSQL
# ==============================
db.url=jdbc:mysql://localhost:3306/sistema_portafolio?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
db.username=root
db.password=914634449
